Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: demo-bucket-123411

  UploadFiles:
    Type: Custom::S3Upload
    Properties:
      ServiceToken: !GetAtt UploadLambda.Arn
      BucketName: !Ref S3Bucket
      Files:
        - Source: https://raw.githubusercontent.com/anshsinghal2002/Cloudformation-POC/main/python_scripts/lambda_function.zip
          Destination: scripts/lambda_start.zip
        - Source: https://raw.githubusercontent.com/anshsinghal2002/Cloudformation-POC/main/python_scripts/lambda_handler.zip
          Destination: scripts/lambda_status.zip

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: S3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:GetObject
                Resource: !Sub '${S3Bucket.Arn}/*'

  UploadLambda:
    Type: AWS::Lambda::Function
    Properties:
      Handler: index.handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        ZipFile: |
          import boto3
          import cfnresponse
          import urllib.request

          s3 = boto3.client('s3')

          def handler(event, context):
            try:
              bucket = event['ResourceProperties']['BucketName']
              files = event['ResourceProperties']['Files']
              
              for file in files:
                urllib.request.urlretrieve(file['Source'], '/tmp/tempfile')
                s3.upload_file('/tmp/tempfile', bucket, file['Destination'])
              
              cfnresponse.send(event, context, cfnresponse.SUCCESS, {})
            except Exception as e:
              print(e)
              cfnresponse.send(event, context, cfnresponse.FAILED, {})

      Runtime: python3.8

  StartCrawlerFunction:
    Type: AWS::Lambda::Function
    DependsOn: UploadFiles
    Properties:
      FunctionName: start-crawler-function
      Handler: lambda_start.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        S3Bucket: !Ref S3Bucket
        S3Key: scripts/lambda_start.zip
      Runtime: python3.8

  GetCrawlerStatusFunction:
    Type: AWS::Lambda::Function
    DependsOn: StartCrawlerFunction
    Properties:
      FunctionName: get-crawler-status
      Handler: lambda_status.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        S3Bucket: !Ref S3Bucket
        S3Key: scripts/lambda_status.zip
      Runtime: python3.8